config/routes.rb
RecipeAnalyzer::Application.routes.draw do
  resources :tags do
    resources :display_names
    resources :ingredients
  end

  resources :display_names do
    resources :tags
  end

  resources :ingredient_names

  resources :locales

  resources :ingredients_names

  resources :ingredients do
    resources :tags
  end

  resources :users do
    resources :recipes
  end

  resources :recipes

  root :to => 'recipes#index'

end

app/models/display_name.rb
#encoding: utf-8
class DisplayName < ActiveRecord::Base

  belongs_to :tag
  belongs_to :locale
  accepts_nested_attributes_for :tag
  attr_accessible :text, :locale_id, :tag, :tag_id



  # METHODS defining the 14 main allergens display_names in languages (in order or query conditions): ENGLISH, FRENCH, GERMAN.
  # Gets the display_names only.
  # As many query conditions as number of languages. If less, see each self method commented notes.
  # USE THESE METHODS/SCOPES TO QUERY INGREDIENTS OR INGREDIENT_NAMES THAT ARE RELATED TO THIS DISPLAY_NAMES THROUGH TAGS.

  # 1 GLUTEN
  def self.contains_gluten
    where(:text => "Gluten")
  end

  # 2 SHELLFISH
  def self.contains_shellfish
    where("text = 'Shellfish' OR text = 'Crustacés' OR text = 'Krebstiere'")
  end

  # 3 EGG
  def self.contains_egg
    where("text = 'Egg' OR text = 'Œuf' OR text = 'Ei'")
  end

  # 4 FISH
  def self.contains_fish
    where("text = 'Fish' OR text = 'Poisson' OR text = 'Fisch'")
  end

  # 5 PEANUT
  def self.contains_peanut
    where("text = 'Peanut' OR text = 'Arachide' OR text = 'Erdnuss'")
  end

  # 6 SOJA. Note: same display_name 'Soja' in ENGLISH, FRENCH, GERMAN
  def self.contains_soja
    where("text = 'Soja'")
  end

  # 7 MILK
  def self.contains_milk
    where("text = 'Milk' OR text = 'Lait' OR text = 'Milch'")
  end

  # 8 NUTS
  def self.contains_nuts
    where("text = 'Nuts' OR text = 'Fruits à coque' OR text = 'Nüsse'")
  end

  # 9 CELERY
  def self.contains_celery
    where("text = 'Celery' OR text = 'Céleri' OR text = 'Sellerie'")
  end

  # 10 MUSTARD
  def self.contains_mustard
    where("text = 'Mustard' OR text = 'Moutarde' OR text = 'Senf'")
  end

  # 11 SESAME
  def self.contains_sesame
    where("text = 'Sesame' OR text = 'Sésame' OR text = 'Sesam'")
  end

  # 12 SULFITE
  def self.contains_sulfite
    where("text = 'Sulfite' OR text = 'Sulphites' OR text = 'Schwefel'")
  end

  # 13 LUPIN. Note: Same display_name 'Lupin' in ENGLISH, FRENCH
  def self.contains_lupin
    where("text = 'Lupin' OR text = 'Lupinen'")
  end

  # 14 MOLLUSCS
  def self.contains_molluscs
    where("text = 'Molluscs' OR text = 'Mollusques' OR text = 'Weichtiere'")
  end

  # SCOPES
  # named scopes calling self methods to get the allergens display_names from 14 main allergens
  scope :gluten, contains_gluten
  scope :shellfish, contains_shellfish
  scope :egg, contains_egg
  scope :fish, contains_fish
  scope :peanut, contains_peanut
  scope :soja, contains_soja
  scope :milk, contains_milk
  scope :nuts, contains_nuts
  scope :celery, contains_celery
  scope :mustard, contains_mustard
  scope :sesame, contains_sesame
  scope :sulfite, contains_sulfite
  scope :lupin, contains_lupin
  scope :molluscs, contains_molluscs

  # Usage Example: (rails console) calling 'DisplayName.gluten' gives the DisplayNames objects matching contains_gluten method conditions.

end

app/controllers/display_names_controller.rb
class DisplayNamesController < ApplicationController
  # GET /display_names
  # GET /display_names.json
  def index
    @display_names = DisplayName.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @display_names }
    end
  end

  # GET /display_names/1
  # GET /display_names/1.json
  def show
    @display_name = DisplayName.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @display_name }
    end
  end

  # GET /display_names/new
  # GET /display_names/new.json
  def new
    @display_name = DisplayName.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @display_name }
    end
  end

  # GET /display_names/1/edit
  def edit
    @display_name = DisplayName.find(params[:id])
  end

  # POST /display_names
  # POST /display_names.json
  def create
    @display_name = DisplayName.new(params[:display_name])

    respond_to do |format|
      if @display_name.save
        format.html { redirect_to @display_name, notice: 'Display name was successfully created.' }
        format.json { render json: @display_name, status: :created, location: @display_name }
      else
        format.html { render action: "new" }
        format.json { render json: @display_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /display_names/1
  # PUT /display_names/1.json
  def update
    @display_name = DisplayName.find(params[:id])

    respond_to do |format|
      if @display_name.update_attributes(params[:display_name])
        format.html { redirect_to @display_name, notice: 'Display name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @display_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /display_names/1
  # DELETE /display_names/1.json
  def destroy
    @display_name = DisplayName.find(params[:id])
    @display_name.destroy

    respond_to do |format|
      format.html { redirect_to display_names_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/display_names_helper.rb
module DisplayNamesHelper
end

app/views/display_names/_form.html.erb
<%= form_for(@display_name) do |f| %>
  <% if @display_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@display_name.errors.count, "error") %> prohibited this display_name from being saved:</h2>

      <ul>
      <% @display_name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :locale %><br />
    <%= f.select :locale_id, Locale.all.collect { |locale|  [locale.language, locale.id] } %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/display_names/edit.html.erb
<h1>Editing display_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @display_name %> |
<%= link_to 'Back', display_names_path %>

app/views/display_names/index.html.erb
<h1>Listing display_names</h1>

<table>
  <tr>
    <th>Locale</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @display_names.each do |display_name| %>
  <tr>
    <td><%= display_name.locale.language %></td>
    <td><%= display_name.text %></td>
    <td><%= link_to 'Show', display_name %></td>
    <td><%= link_to 'Edit', edit_display_name_path(display_name) %></td>
    <td><%= link_to 'Destroy', display_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Display name', new_display_name_path %>

app/views/display_names/new.html.erb
<h1>New display_name</h1>

<%= render 'form' %>

<%= link_to 'Back', display_names_path %>

app/views/display_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Locale:</b>
  <%= @display_name.locale.language %>
</p>

<p>
  <b>Text:</b>
  <%= @display_name.text %>
</p>


<%= link_to 'Edit', edit_display_name_path(@display_name) %> |
<%= link_to 'Back', display_names_path %>