config/routes.rb
RecipeAnalyzer::Application.routes.draw do
  resources :tags do
    resources :display_names
    resources :ingredients
  end

  resources :display_names do
    resources :tags
  end

  resources :ingredient_names

  resources :locales

  resources :ingredients_names

  resources :ingredients do
    resources :tags
  end

  resources :users do
    resources :recipes
  end

  resources :recipes

  root :to => 'recipes#index'

end

app/models/locale.rb
class Locale < ActiveRecord::Base
  has_many :display_names
  attr_accessible :language, :display_names

end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
  # GET /locales
  # GET /locales.json
  def index
    @locales = Locale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locales }
    end
  end

  # GET /locales/1
  # GET /locales/1.json
  def show
    @locale = Locale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @locale }
    end
  end

  # GET /locales/new
  # GET /locales/new.json
  def new
    @locale = Locale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @locale }
    end
  end

  # GET /locales/1/edit
  def edit
    @locale = Locale.find(params[:id])
  end

  # POST /locales
  # POST /locales.json
  def create
    @locale = Locale.new(params[:locale])

    respond_to do |format|
      if @locale.save
        format.html { redirect_to @locale, notice: 'Locale was successfully created.' }
        format.json { render json: @locale, status: :created, location: @locale }
      else
        format.html { render action: "new" }
        format.json { render json: @locale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locales/1
  # PUT /locales/1.json
  def update
    @locale = Locale.find(params[:id])

    respond_to do |format|
      if @locale.update_attributes(params[:locale])
        format.html { redirect_to @locale, notice: 'Locale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @locale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locales/1
  # DELETE /locales/1.json
  def destroy
    @locale = Locale.find(params[:id])
    @locale.destroy

    respond_to do |format|
      format.html { redirect_to locales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/views/locales/_form.html.erb
<%= form_for(@locale) do |f| %>
  <% if @locale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locale.errors.count, "error") %> prohibited this locale from being saved:</h2>

      <ul>
      <% @locale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locales/edit.html.erb
<h1>Editing locale</h1>

<%= render 'form' %>

<%= link_to 'Show', @locale %> |
<%= link_to 'Back', locales_path %>

app/views/locales/index.html.erb
<h1>Listing locales</h1>

<table>
  <tr>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locales.each do |locale| %>
  <tr>
    <td><%= locale.language %></td>
    <td><%= link_to 'Show', locale %></td>
    <td><%= link_to 'Edit', edit_locale_path(locale) %></td>
    <td><%= link_to 'Destroy', locale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Locale', new_locale_path %>

app/views/locales/new.html.erb
<h1>New locale</h1>

<%= render 'form' %>

<%= link_to 'Back', locales_path %>

app/views/locales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Language:</b>
  <%= @locale.language %>
</p>


<%= link_to 'Edit', edit_locale_path(@locale) %> |
<%= link_to 'Back', locales_path %>