config/routes.rb
RecipeAnalyzer::Application.routes.draw do
  resources :tags do
    resources :display_names
    resources :ingredients
  end

  resources :display_names do
    resources :tags
  end

  resources :ingredient_names

  resources :locales

  resources :ingredients_names

  resources :ingredients do
    resources :tags
  end

  resources :users do
    resources :recipes
  end

  resources :recipes

  root :to => 'recipes#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  has_many :ingredients_tags
  has_many :tags, :through => :ingredients_tags
  has_many :ingredient_names

  accepts_nested_attributes_for :tags
  accepts_nested_attributes_for :ingredients_tags

  attr_accessible :name_EN, :source, :tags, :tag_ids, :tags_attributes

  validates_presence_of :name_EN ,:on => :create, :message => "Field can't be blank"
  validates_presence_of :name_EN, :on => :update
  validates_uniqueness_of :name_EN



end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])
    @tag= @ingredient.tags.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new
    @tag= @ingredient.tags.build


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
    @tag= @ingredient.tags.build
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    params[:ingredient][:tag_ids] ||= []
    @ingredient = Ingredient.new(params[:ingredient])
    @tag= @ingredient.tags.build

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    params[:ingredient][:tag_ids] ||= []
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper

end

app/views/ingredients/_form.html.erb
<%= simple_form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name_EN, :label=> "Name", :required => true %>
  </div>

  <div class="field">
    <%= f.association :tags,
                      :collection => Tag.all(:order => 'id'),
                      :as => :check_boxes,
                      :multiple => true,
                      :label => 'Choose tags to attach to this ingredient<br/>',
                      label_method: :id,
                      value_method: :id,
                      include_blank: true %>

  </div>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient_fields.html.erb
<%= f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', :f => builder %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>id</th>
    <th>Name en</th>
    <th>Tags</th>
    <th>Source</th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.id %></td>
    <td><%= ingredient.name_EN %></td>
    <td><%= join_ingredient_tag_ids(ingredient) %> </td>
    <td><%= ingredient.source %></td>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name en:</b>
  <%= @ingredient.name_EN %>
</p>

<p>
  <b>Source:</b>
  <%= @ingredient.source %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>