config/routes.rb
RecipeAnalyzer::Application.routes.draw do
  resources :tags do
    resources :display_names
    resources :ingredients
  end

  resources :display_names do
    resources :tags
  end

  resources :ingredient_names

  resources :locales

  resources :ingredients_names

  resources :ingredients do
    resources :tags
  end

  resources :users do
    resources :recipes
  end

  resources :recipes

  root :to => 'recipes#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :display_names
  has_many :ingredients, :through => :ingredients_tags
  has_many :recipes, :through => :recipes_tags
  has_many :recipes_tags
  has_many :ingredients_tags

  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :ingredients_tags

  attr_accessible :title, :body, :display_name_ids , :ingredients, :display_names, :ingredient_id, :ingredients_attributes
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <b>A Tag is a group of Display_names linking to a same Ingredient.</b><br/>
  For example, Ingredient with name 'almonds' refers to the following Display_names:<br/>
  14 : 'Nuts',<br/>
  21 : 'nuts (almonds)',<br/>
  36 : 'Fruits à coque',<br/>
  43 : 'Fruits à coque (amandes)',<br/>
  58 : 'Nüsse',<br/>
  65 : 'Nüsse (Mandeln)'<br/>
  <br/>
  Tag with id 8 is generically called "Nuts" and englobes display_names [14,36,58].<br/>
  Tag with id 15 is generically called "Nuts (almonds)" and takes display_names [21,43,65].<br/>

</p>
  <div class="field">

    <%= f.association :display_names, :as => :check_boxes, :multiple => true,
                      :label => 'Choose Display names contained in the tag you want to create<br/>',
                      label_method: :text, value_method: :id, include_blank: true


    %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>id</th>
    <th>Display names</th>

    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.id %></td>
    <td><%= tag.display_names.map {|dn| dn.text.to_s}.join(', ') %></td>

    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tag : <%=  @tag.id %></b>
</p>
<table>
  <tr>
    <td>
      <b>Display names</b>
    </td>
    <td>
      <b>Locale</b>
    </td>
  </tr>
  <% @tag.display_names.each do |dn| %>
      <tr>
        <td>
          <%= dn.text %>
        </td>
        <td>
          <%= dn.locale.language %>
        </td>
      </tr>
  <% end %>
</table>



<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>